import { createServer, type IncomingMessage, type Server, type ServerResponse } from 'node:http';
import { createServer as createHttpsServer, type Server as HttpsServer } from 'node:https';
import { readFileSync } from 'node:fs';
import { performance } from 'node:perf_hooks';

import { ErrorCodes, TelagentError } from '@telagent/protocol';

import { extractBearerToken } from './auth.js';
import { Router } from './router.js';
import { problem } from './response.js';
import { attachmentRoutes } from './routes/attachments.js';
import { groupRoutes } from './routes/groups.js';
import { identityRoutes } from './routes/identities.js';
import { keyRoutes } from './routes/keys.js';
import { messageRoutes } from './routes/messages.js';
import { nodeRoutes } from './routes/node.js';
import { contactRoutes } from './routes/contacts.js';
import { conversationRoutes } from './routes/conversations.js';
import { ownerRoutes } from './routes/owner.js';
import { clawnetRoutes } from './routes/clawnet.js';
import { profileRoutes } from './routes/profile.js';
import { sessionRoutes } from './routes/session.js';
import { walletRoutes } from './routes/wallets.js';
import { handleRelayRequest } from './routes/relay.js';
import { eventRoutes } from './routes/events.js';
import type { RuntimeContext } from './types.js';

function buildRouter(ctx: RuntimeContext): Router {
  const router = new Router();

  router.mount('/api/v1/node', nodeRoutes(ctx));
  router.mount('/api/v1/identities', identityRoutes(ctx));
  router.mount('/api/v1/groups', groupRoutes(ctx));
  router.mount('/api/v1/keys', keyRoutes(ctx));
  router.mount('/api/v1/wallets', walletRoutes(ctx));
  router.mount('/api/v1/messages', messageRoutes(ctx));
  router.mount('/api/v1/conversations', conversationRoutes(ctx));
  router.mount('/api/v1/contacts', contactRoutes(ctx));
  router.mount('/api/v1/owner', ownerRoutes(ctx));
  router.mount('/api/v1/attachments', attachmentRoutes(ctx));
  router.mount('/api/v1/session', sessionRoutes(ctx));
  router.mount('/api/v1/clawnet', clawnetRoutes(ctx));
  router.mount('/api/v1/profile', profileRoutes(ctx));
  router.mount('/api/v1/events', eventRoutes(ctx));

  return router;
}

/**
 * Global auth gate — runs before route dispatch.
 * Whitelisted paths are allowed without a session token.
 * Everything else requires a valid tses_* session.
 */
const AUTH_WHITELIST: Array<{ method?: string; path: string }> = [
  { method: 'POST', path: '/api/v1/session/unlock' },
  { path: '/api/v1/node' },
  { path: '/api/v1/identities/self' },
  { method: 'GET', path: '/api/v1/profile' },
  { method: 'GET', path: '/api/v1/profile/avatar' },
  // Attachments: GET is public (peers download images), PUT uses objectKey as a capability token
  // (objectKey is a UUID generated by initUpload which requires auth — same model as presigned URLs)
  { method: 'GET', path: '/api/v1/attachments' },
  { method: 'PUT', path: '/api/v1/attachments' },
  // GET /api/v1/profile/:did — cached peer profiles are public
  // (matched via startsWith in isAuthExempt since :did varies)
  // Relay routes — auth is enforced on the target node side
  { path: '/relay' },
  // Local SSE events — auth enforced separately (session token in query)
  { method: 'GET', path: '/api/v1/events' },
];

function isAuthExempt(method: string, pathname: string): boolean {
  for (const rule of AUTH_WHITELIST) {
    if (rule.method && rule.method !== method) continue;
    if (pathname === rule.path || pathname.startsWith(rule.path + '/')) return true;
  }
  return false;
}

function requireGlobalAuth(req: IncomingMessage, pathname: string, ctx: RuntimeContext): void {
  const method = req.method || 'GET';
  if (method === 'OPTIONS') return;
  if (!pathname.startsWith('/api/v1/')) return; // only enforce on API routes
  if (isAuthExempt(method, pathname)) return;

  const token = extractBearerToken(req.headers as Record<string, string | string[] | undefined>);
  if (!token) {
    throw new TelagentError(ErrorCodes.UNAUTHORIZED, 'Authentication required');
  }
  if (!token.startsWith('tses_')) {
    throw new TelagentError(ErrorCodes.UNAUTHORIZED, 'Invalid token format. Expected session token (tses_*).');
  }
  const info = ctx.sessionManager.getSessionInfo(token);
  if (!info || !info.active) {
    throw new TelagentError(ErrorCodes.UNAUTHORIZED, 'Session expired or invalid');
  }
}

export class ApiServer {
  private server: Server | null = null;
  private secureServer: HttpsServer | null = null;
  private readonly router: Router;

  constructor(private readonly ctx: RuntimeContext) {
    this.router = buildRouter(ctx);
  }

  private createRequestHandler() {
    return async (req: IncomingMessage, res: ServerResponse) => {
      const parsedUrl = new URL(req.url || '/', 'http://127.0.0.1');
      const startedAt = performance.now();
      res.once('finish', () => {
        this.ctx.monitoringService.recordHttpRequest({
          method: req.method || 'UNKNOWN',
          path: parsedUrl.pathname,
          status: res.statusCode,
          durationMs: performance.now() - startedAt,
        });
      });

      res.setHeader('Access-Control-Allow-Origin', '*');
      res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
      res.setHeader('Access-Control-Allow-Methods', 'GET,POST,PUT,DELETE,OPTIONS');

      if (req.method === 'OPTIONS') {
        res.writeHead(204);
        res.end();
        return;
      }

      try {
        requireGlobalAuth(req, parsedUrl.pathname, this.ctx);
      } catch (error) {
        const authErr = error instanceof TelagentError ? error : new TelagentError(ErrorCodes.UNAUTHORIZED, 'Authentication required');
        problem(res, authErr.toProblem(req.url));
        return;
      }

      // Handle /relay/* before standard router (relay needs wildcard path matching)
      try {
        const relayHandled = await handleRelayRequest(req, res, parsedUrl.pathname, this.ctx);
        if (relayHandled) return;
      } catch (error) {
        if (res.headersSent) return;
        const internal = error instanceof TelagentError ? error : new TelagentError(ErrorCodes.INTERNAL, error instanceof Error ? error.message : 'Unexpected error');
        problem(res, internal.toProblem(req.url));
        return;
      }

      try {
        const matched = await this.router.handle(req, res);
        if (!matched && !res.headersSent) {
          const notFound = new TelagentError(ErrorCodes.NOT_FOUND, 'Route not found');
          problem(res, notFound.toProblem(req.url));
        }
      } catch (error) {
        if (res.headersSent) {
          return;
        }
        const internal = error instanceof TelagentError ? error : new TelagentError(ErrorCodes.INTERNAL, error instanceof Error ? error.message : 'Unexpected error');
        problem(res, internal.toProblem(req.url));
      }
    };
  }

  async start(): Promise<void> {
    if (this.server || this.secureServer) {
      return;
    }

    const { tls } = this.ctx.config;

    if (tls) {
      // ── HTTPS mode: main traffic on HTTPS, HTTP redirects to HTTPS ──
      const cert = readFileSync(tls.certPath);
      const key = readFileSync(tls.keyPath);

      this.secureServer = createHttpsServer({ cert, key }, this.createRequestHandler());
      await new Promise<void>((resolve) => {
        this.secureServer!.listen(tls.httpsPort, this.ctx.config.host, resolve);
      });

      // HTTP → HTTPS redirect server (with CORS so browsers can follow the redirect)
      const httpsPort = tls.httpsPort;
      const redirectHost = this.ctx.config.host;
      this.server = createServer((req, res) => {
        res.setHeader('Access-Control-Allow-Origin', '*');
        res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
        res.setHeader('Access-Control-Allow-Methods', 'GET,POST,PUT,DELETE,OPTIONS');
        if (req.method === 'OPTIONS') {
          res.writeHead(204);
          res.end();
          return;
        }
        const host = req.headers.host?.replace(/:\d+$/, '') || redirectHost;
        const location = `https://${host}${httpsPort === 443 ? '' : ':' + httpsPort}${req.url || '/'}`;
        res.writeHead(301, { Location: location });
        res.end();
      });
      await new Promise<void>((resolve) => {
        this.server!.listen(this.ctx.config.port, this.ctx.config.host, resolve);
      });
    } else {
      // ── Plain HTTP mode (default, unchanged) ──
      this.server = createServer(this.createRequestHandler());
      await new Promise<void>((resolve) => {
        this.server!.listen(this.ctx.config.port, this.ctx.config.host, resolve);
      });
    }
  }

  async stop(): Promise<void> {
    const closeServer = (s: Server | HttpsServer) =>
      new Promise<void>((resolve) => { s.close(() => resolve()); });

    const tasks: Promise<void>[] = [];
    if (this.secureServer) {
      tasks.push(closeServer(this.secureServer));
      this.secureServer = null;
    }
    if (this.server) {
      tasks.push(closeServer(this.server));
      this.server = null;
    }
    await Promise.all(tasks);
  }

  get httpServer(): Server | null {
    return this.server;
  }

  get httpsServer(): HttpsServer | null {
    return this.secureServer;
  }
}
